name: Sync to HuggingFace hub
on: 
  push:
    branches: [main]
    
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fectch-dept: 0

      - name: Unshallow the repo
        run: |
          git fetch --unshallow
        
      - name: Add remote
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: 
          git remote add space https://iNicoNavarro:$HF@huggingface.co/spaces/iNicoNavarro/mlops_experiments
      - name: Push to hub
        env:
          HF: ${{ secrets.HUGGINGFACE }}      
        run:
          git push --force https://iNicoNavarro:$HF@huggingface.co/spaces/iNicoNavarro/mlops_experiments main
